DROP DATABASE UNI;
CREATE DATABASE UNI;
USE UNI;
CREATE TABLE STUD(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL,
EMAIL VARCHAR(10) UNIQUE
);
CREATE TABLE DEP(
DEPARTID INT PRIMARY KEY,
NAME VARCHAR(50)
);
CREATE TABLE STAFF(
DEPID INT,
FOREIGN KEY (DEPID) REFERENCES DEP(DEPARTID), 
NAME VARCHAR(50),
AGE INT CHECK (AGE>18)
);
CREATE TABLE ORDERS(
ORDERID INT ,
STATUS VARCHAR(20) DEFAULT 'PENDING'
);
CREATE TABLE CUSTOMER(
CID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) DEFAULT 'HAMZA'
);
CREATE TABLE HUMAN(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);
CREATE TABLE TEST(
ID INT,
NAME VARCHAR(100)
);
INSERT INTO TEST VALUES (1,'JAWAD'),(2,'ALI');
TRUNCATE TABLE TEST;
ALTER TABLE TEST RENAME TO MYTEST12;
ALTER TABLE MYTEST12 RENAME TO TEST;
ALTER TABLE TEST CHANGE MYNAME MYNAME VARCHAR(10);
ALTER TABLE HUMAN ADD AGE INT;
ALTER TABLE HUMAN DROP AGE;
ALTER TABLE HUMAN MODIFY NAME VARCHAR(70);
ALTER TABLE HUMAN CHANGE NAME FULLNAME VARCHAR(10);
ALTER TABLE HUMAN DROP COLUMN FULLNAME;
ALTER TABLE HUMAN MODIFY ID BIGINT;
ALTER TABLE HUMAN ADD AGE INT;
ALTER TABLE HUMAN DROP ID;
ALTER TABLE HUMAN CHANGE AGE MYAGE VARCHAR(100);
DROP TABLE HUMAN;
INSERT INTO STUD VALUES (1,'ALI',25,'JAWAD@'),(2,'JAWAD',30,'JAWAD1@'); 
INSERT INTO DEP VALUES (1,'IT'),(2,'TECH'); 
INSERT INTO STAFF VALUES (1,'AHMED',20),(2,'JAWAD',19); 
INSERT INTO ORDERS (ORDERID) VALUES (1);
INSERT INTO ORDERS VALUES (1,DEFAULT);
INSERT INTO ORDERS VALUES (5,'DELIVERED');
INSERT INTO CUSTOMER VALUES (),();
INSERT INTO CUSTOMER(NAME) VALUES('USMAN'),('KAMRAN');
CREATE INDEX CINDEX
ON  CUSTOMER(CID,NAME);
SHOW INDEX FROM CUSTOMER;
DROP INDEX CINDEX 
ON CUSTOMER;
SHOW INDEX FROM CUSTOMER;
CREATE VIEW ALLVIEW AS
SELECT AGE,CID,STATUS
FROM STUD,CUSTOMER,ORDERS
WHERE CID>1;
DROP VIEW ALLVIEW;
SELECT * FROM ALLVIEW WHERE CID>3;
SELECT NAME,STATUS,CID FROM UNI.CUSTOMER,UNI.ORDERS WHERE STATUS='PENDING';
