CREATE DATABASE FRESHMART; #CREATE DATABASE
USE FRESHMART;
CREATE TABLE Products( #CREATE A TABLE FOR PRODUCTS
prodID INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
category VARCHAR(30),
price DECIMAL(8,2),
stock INT
);
#CREATE A TABLE FOR SUPPLIERS
CREATE TABLE Suppliers(
supID INT PRIMARY KEY AUTO_INCREMENT,
supName VARCHAR(50) NOT NULL,
city VARCHAR(30) DEFAULT 'Islamabad',
phone VARCHAR(15)
);
#CREATE A TABLE FOR ORDERS:
CREATE TABLE Orders(
orderID INT PRIMARY KEY AUTO_INCREMENT,
prodID INT,
quantity INT,
orderDate DATE
);
#INSERT VALUES INTO PRODUCT TABLE:
INSERT INTO Products(name, category, price, stock) VALUES ('milk','Dairy',333.7,3),('nuggets','FROZEN',433.2,4),('juice','DRINKS',32.1,5),('lays','SNACKS',222.2,6),('surf','DETERGENTS',119.2,7);

#INSERT VALUES INTO SUPPLIER TABLE:
INSERT INTO Suppliers(supName, city, phone) VALUES ('TUBA',DEFAULT,051-2334678),('USMAN','Lahore',051-2334675),('SARA',DEFAULT,051-2334674),('HAMZA','Lahore',051-2334673),('ALI',DEFAULT,051-2334672);

#INSERT VALUES INTO ORDER TABLE:
INSERT INTO Orders (prodID,quantity,orderDate) VALUES (1,2,'2025-09-22'),(2,3,'2004-12-3'),(3,4,'2004-12-4'),(4,5,'2026-09-22'),(5,6,'2004-12-6');

#CREATE INDEX FOR PRODUCT TABLE NAME COLUMN:
CREATE INDEX id1 ON Products(name);
SHOW INDEXES FROM Products;
#MAKE A CREATE VIEW TABLE FOR PRODUCTS:
CREATE VIEW product_overview AS
SELECT name,category,price
FROM ProduCts;

#DISPLAY ALL PRODUCTS WITH CONDITIONS MET:
SELECT* FROM Products WHERE category ='Dairy';
SELECT* FROM Products WHERE price >200;
#DISPLAY ALL ORDERS WITH CONDITIONS MET:
SELECT* FROM Orders WHERE orderDate >='2025-09-22';
#DISPLAY ALL SUUPLIERS WITH CONDITIONS MET:
SELECT* FROM Suppliers WHERE city ='Lahore';

#RETRIEVE ALL DATA FROM CREATE VIEW  WITH CONDITIONS MET:
SELECT* FROM product_overview WHERE price <300;