DROP DATABASE UNIVERSITY;
CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;
CREATE TABLE department(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL, 
headname TEXT,
Location VARCHAR(50) DEFAULT 'Islamabad', 
Code INT UNIQUE
);
CREATE TABLE employee(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL, 
fathername TEXT,
Phone VARCHAR(11) DEFAULT'051-1234567',
address TEXT,
salary FLOAT,
DeptID INT,
FOREIGN KEY (DeptID) REFERENCES department(ID)
);
CREATE TABLE supplier(
ID INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL, 
owner TEXT,
address TEXT,
city VARCHAR(20) DEFAULT 'Islamabad',
typeID INT
);
CREATE TABLE inventory(
ID INT PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
cetegoryID INT,
items INT,
price FLOAT
);