CREATE DATABASE MYCASE;
USE MYCASE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(10)
);
CREATE TABLE SUBJECT(
CID INT,
SID INT,
SNAME VARCHAR(20),
FOREIGN KEY (SID) REFERENCES STUDENT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
INSERT INTO STUDENT VALUES(1,'ALI'),(2,'QASIM'),(3,'AHMED'),(4,'ZUBAIR');
INSERT INTO SUBJECT VALUES(101,1,'ALI'),(102,2,'QASIM'),(103,3,'AHMED'),(104,4,'ZUBAIR');
ALTER TABLE SUBJECT ADD CNAME VARCHAR(10);
UPDATE SUBJECT SET CNAME ='DE' WHERE SID=1 ;
UPDATE SUBJECT SET CNAME ='STAT' WHERE SID=2 ;
UPDATE SUBJECT SET CNAME ='DB' WHERE SID=3 ;
UPDATE SUBJECT SET CNAME ='MATH' WHERE SID=4 ;
SET SQL_SAFE_UPDATES=0;
DELETE FROM SUBJECT 
WHERE CID IS NULL 
  AND SID IS NULL 
  AND SNAME IS NULL
  AND CNAME IS NOT NULL;
UPDATE STUDENT SET ID=10 WHERE ID=2;
UPDATE STUDENT SET ID =100 WHERE ID=3;
DELETE FROM STUDENT WHERE ID =1;
SELECT* FROM SUBJECT;
SELECT CID,SNAME FROM SUBJECT;
SELECT CID,SNAME FROM SUBJECT WHERE CID=103;
