CREATE DATABASE STUD;
USE STUD;
CREATE TABLE STUDENT(
ID INT,
NAME CHAR(10)
);
CREATE TABLE STUDS(
SID INT,
SNAME CHAR(20)
);
CREATE DATABASE COURSES;
USE COURSES;
CREATE TABLE C1(
SID INT,
SNAME CHAR(20),
SAGE INT,
CNAME VARCHAR(10),
CID INT
);
ALTER TABLE STUDENT CHANGE NAE NAME VARCHAR(20);
INSERT INTO STUDENT VALUES (1,'ALI'),(2,'JAWAD');
SET SQL_SAFE_UPDATES=0;
DELETE FROM STUD.STUDENT WHERE NAME='ALI';
INSERT INTO STUDENT(ID,NAME) VALUES (3,'AHMED');
INSERT INTO STUDENT VALUES (4,'SALMAN');
INSERT INTO STUDS SELECT ID, NAME FROM STUDENT WHERE NAME='ALI';
ALTER TABLE STUDS ADD COLUMN AGE INT;
ALTER TABLE STUDS ADD COLUMN SCHOOL VARCHAR(30);
INSERT INTO STUDS SELECT ID,NAME,20,'ROOTS' FROM STUDENT WHERE NAME='JAWAD';
INSERT INTO COURSES.C1 SELECT SID,SNAME,AGE,'DB',001 FROM STUD.STUDS WHERE SNAME='JAWAD';
INSERT INTO COURSES.C1 VALUES (11,'AHMED',23,'ML',003),(11,'FARAZ',21,'AI',002),(11,'DANIA',26,'CS',004),(11,'ZUBAIR',25,'IS',005);
UPDATE C1 SET SAGE=2 WHERE SID=11;
DELETE FROM C1;
DELETE FROM C1 WHERE CID=2;
SET SQL_SAFE_UPDATES=1;
