CREATE DATABASE SALES;
USE SALES;
CREATE TABLE SALE(
ID INT,
NAME VARCHAR(50),
REGION VARCHAR(50),
SALES INT
);
INSERT INTO SALE VALUES(1,'JAWAD','NORTH',2000),(2,'ALI','EAST',5000),(3,'SANA','SOUTH',4000),(4,'RAZA','NORTH',3000),(5,'FARAZ','SOUTH',2000),(6,'AHMED','EAST',1000);
SELECT REGION,COUNT(ID) AS TOTALEMP
FROM SALE
GROUP BY REGION;
SELECT REGION,SUM(SALES) AS TOTALSALES
FROM SALE
GROUP BY REGION;
SELECT REGION,AVG(SALES) AS AVGSALES
FROM SALE
GROUP BY REGION;
SELECT REGION,MIN(SALES) AS MINSALES
FROM SALE
GROUP BY REGION;
SELECT REGION,MAX(SALES) AS MAXSALES
FROM SALE 
GROUP BY REGION;
SELECT REGION, 
COUNT(NAME) AS TOTALEMP,
SUM(SALES) AS TOTALSALES,
AVG(SALES) AS AVGSALES,
MIN(SALES) AS LOWESTSALES,
MAX(SALES) AS HIGHESTSALES
FROM SALE
GROUP BY REGION;