CREATE DATABASE PRAC;
USE PRAC;
CREATE TABLE P1(
FIRSTNAME VARCHAR(10),
SECONDNAME VARCHAR(10)
);
INSERT INTO P1 VALUES('AHMED','ALI'),('JAKE','PAUL'),('LOGAN','PAUL'),('QASIM','KHAN');
SELECT FIRSTNAME AS FN,SECONDNAME AS SN FROM P1;
SELECT FIRSTNAME,SECONDNAME FROM P1;
SELECT* FROM P1;

USE SSCASE;
DROP TABLE STUDENTS;
CREATE TABLE STUDENTS(
STUDENTID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPARTMENT VARCHAR(40),
MARKS INT,
AGE INT,
CITY VARCHAR(50),
ADMISSION DATE,
FEE DECIMAL(10,2)
);
INSERT INTO STUDENTS VALUES 
 (2, 'Sara Ahmed', 'Mathematics', 76, 19, 'Karachi', '2021-08-15', 48000),
 (3, 'Bilal Iqbal', 'Physics', 64, 22, 'Islamabad', '2023-01-10', 50000),
 (4, 'Ayesha Noor', 'Computer Science', 59, 17, 'Lahore', '2020-07-05', 45000),
 (5, 'Usman Raza', 'Chemistry', 92, 24, 'Faisalabad', '2021-12-20', 60000),
 (6, 'Fatima Zahra', 'Mathematics', 40, 18, 'Multan', '2023-03-01', 30000);
 SELECT * FROM STUDENTS WHERE DEPARTMENT='Computer Science';
 SELECT* FROM STUDENTS WHERE CITY <> 'Lahore';
 SELECT* FROM STUDENTS WHERE MARKS>80;
 SELECT* FROM STUDENTS WHERE AGE<18;
 SELECT* FROM STUDENTS WHERE FEE>=50000;
 SELECT* FROM STUDENTS WHERE MARKS<=60;
 SELECT* FROM STUDENTS WHERE AGE BETWEEN 18 AND 22;
 SELECT* FROM STUDENTS WHERE NAME LIKE 'A%';
 SELECT* FROM STUDENTS WHERE DEPARTMENT IN('Computer Science','Physics','Mathematics');
 SELECT* FROM STUDENTS WHERE DEPARTMENT ='Computer Science' AND MARKS>70;
 SELECT* FROM STUDENTS WHERE CITY='Lahore' OR CITY='Karachi';
 SELECT* FROM STUDENTS WHERE (DEPARTMENT='Computer Science' OR DEPARTMENT='Mathematics')
 AND MARKS>=75;
 SELECT* FROM STUDENTS WHERE NOT CITY='Lahore';
 SELECT* FROM STUDENTS WHERE DEPARTMENT NOT IN ('Physics','Chemistry');
 SELECT* FROM STUDENTS WHERE (DEPARTMENT='Computer Science' OR DEPARTMENT='Mathematics') AND NOT CITY='Lahore';
 SELECT* FROM STUDENTS WHERE (DEPARTMENT='Computer Science' AND MARKS>70)OR(DEPARTMENT='Mathematics' AND FEE<50000);
 SELECT* FROM STUDENTS WHERE (MARKS BETWEEN 60 AND 90)
 AND (NAME LIKE 'A%' OR NAME LIKE 'S%');
 SELECT* FROM STUDENTS WHERE NAME LIKE 'A_Z';
 SELECT* FROM STUDENTS WHERE NAME LIKE '%AN%';
 SELECT* FROM STUDENTS WHERE NAME LIKE '_AN%';
 SELECT* FROM STUDENTS WHERE NAME LIKE 'A%';
 SELECT* FROM STUDENTS WHERE NAME LIKE '%N';
 SELECT* FROM STUDENTS WHERE NAME LIKE '%RA%';
 SELECT* FROM STUDENTS WHERE NAME LIKE 'A_Z';
 SELECT* FROM STUDENTS WHERE NAME LIKE '_ALI%';
 SELECT* FROM STUDENTS WHERE NAME LIKE '_A%';
 SELECT* FROM STUDENTS WHERE (FEE BETWEEN 50000 AND 80000) AND (DEPARTMENT IN ('HR','MARKETING')AND NAME LIKE'%A%'); 
 SELECT* FROM STUDENTS WHERE (NOT CITY= 'Karachi') AND  (ADMISSION > '2020-01-01');