CREATE DATABASE TT;
USE TT;
CREATE TABLE STUDENT(
STUDENTID INT,
NAME VARCHAR(50),
AGE INT,
DEPARTMENT VARCHAR(50),
MARKS INT
);
CREATE TABLE DEPARTMENT(
DEPTID INT,
DEPTNAME VARCHAR(50),
LOCATION VARCHAR(50)
);
INSERT INTO STUDENT VALUES
(1, 'Ali', 21, 'CS', 78),
(2, 'Sara', 22, 'IT', 85),
(3, 'Ahmed', 20, 'CS', 65),
(4, 'Hina', 19, 'SE', 90),
(5, 'Usman', 23, 'IT', 55);
INSERT INTO DEPARTMENT VALUES
(101, 'CS', 'Block A'),
(102, 'IT', 'Block B'),
(103, 'SE', 'Block C');

SELECT NAME,MARKS FROM STUDENT WHERE MARKS>(SELECT AVG(MARKS)FROM STUDENT);
SELECT NAME FROM STUDENT WHERE DEPARTMENT IN (SELECT DEPTNAME FROM DEPARTMENT WHERE LOCATION ='Block B');
SELECT NAME, MARKS FROM STUDENT WHERE MARKS>ANY (SELECT MARKS FROM STUDENT WHERE DEPARTMENT='IT');
SELECT NAME, MARKS FROM STUDENT WHERE MARKS>ALL (SELECT MARKS FROM STUDENT WHERE DEPARTMENT='CS');
SELECT NAME, MARKS,DEPARTMENT FROM STUDENT S WHERE MARKS>(SELECT AVG(MARKS) FROM STUDENT WHERE DEPARTMENT=S.DEPARTMENT);
SELECT DEPTNAME FROM DEPARTMENT D WHERE EXISTS (SELECT * FROM STUDENT S WHERE D.DEPTNAME=S.DEPARTMENT);
SELECT DEPARTMENT , MAX(MARKS) FROM(SELECT *FROM STUDENT) AS SUB  GROUP BY DEPARTMENT;