DROP DATABASE LIBRARY;
CREATE DATABASE LIBRARY;
USE LIBRARY;
CREATE TABLE BOOKS(
BookID INT,
Title VARCHAR(50),
Author VARCHAR(50),
Price INT
);
CREATE TABLE BORROWERS(
BorrowID INT,
StudentName VARCHAR(50),
BookID INT,
BorrowDate DATE
);
INSERT INTO BOOKS VALUES
(1, 'Database Systems', 'Korth', 500),
(2, 'AI Basics', 'Stuart', 700),
(3, 'Web Development', 'Jonas', 450),
(4, 'Data Science', 'Python', 800),
(5, 'Networks', 'Tanenbaum', 600);
INSERT INTO BORROWERS VALUES
(101, 'Ali', 1, '2024-01-10'),
(102, 'Sara', 2, '2024-01-12'),
(103, 'Ahmed',1, '2024-02-01'),
(104, 'Hina',4, '2024-02-05'),
(105, 'Usman',3, '2024-02-10');

SELECT Title FROM BOOKS WHERE BookID IN (SELECT BookID FROM BORROWERS);
SELECT Title FROM BOOKS WHERE BookID NOT IN (SELECT BookID FROM BORROWERS);
SELECT Title,PRICE FROM BOOKS WHERE PRICE>ANY (SELECT AVG(PRICE) FROM BOOKS);
SELECT TITLE FROM BOOKS B WHERE EXISTS (SELECT * FROM BORROWERS BR WHERE B.BOOKID=BR.BOOKID);
SELECT STUDENTNAME,BOOKID FROM BORROWERS WHERE BOOKID IN (SELECT  BOOKID FROM BOOKS WHERE PRICE>ANY(SELECT AVG(PRICE) FROM BOOKS));
SELECT STUDENTNAME,(SELECT TITLE FROM BOOKS B WHERE B.BOOKID=BR.BOOKID)AS TITLE FROM BORROWERS BR;
######
SELECT Title,Author FROM BOOKS
WHERE BookID IN (SELECT BookID FROM BORROWERS);
SELECT Title,Author FROM BOOKS
WHERE BookID NOT IN (SELECT BookID FROM BORROWERS);
SELECT Title,Author,Price FROM BOOKS
WHERE Price > ALL (SELECT AVG(Price) FROM BOOKS);
SELECT StudentName,BookID FROM BORROWERS
WHERE BookID IN  (SELECT BookID FROM BOOKS WHERE Price>ALL(SELECT AVG(Price)FROM BOOKS));
SELECT Title,Author,Price FROM BOOKS
WHERE BookID = ANY (SELECT BookID FROM BORROWERS);
SELECT StudentName,(SELECT Title FROM BOOKS B WHERE B.BookID=BR.BookID) AS BTITLE FROM BORROWERS BR;

