CREATE DATABASE LSP;
USE LSP;
CREATE TABLE STUDENTS(
STUDENT_ID INT PRIMARY KEY  AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
DEPARTMENT VARCHAR(30) NOT NULL,
GPA DECIMAL(3,2) CHECK (GPA BETWEEN 0.00 AND 4.00)
);
CREATE TABLE COURSES(
COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
COURSE_NAME VARCHAR(50) NOT NULL,
CREDIT_HOURS INT CHECK(CREDIT_HOURS>0)
);
CREATE TABLE ENROLLMENTS(
ENROLL_ID INT PRIMARY KEY AUTO_INCREMENT,
STUDENT_ID INT ,
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
ON UPDATE CASCADE
ON DELETE CASCADE,
COURSE_ID INT,
FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE,
SEMESTER VARCHAR(10) CHECK(SEMESTER IN('SPRING','FALL','SUMMER')),
MARKS INT CHECK(MARKS BETWEEN 0 AND 100)
);
INSERT INTO STUDENTS(NAME,DEPARTMENT,GPA) VALUES('ALI RAZA','CS',3.45),
('SARA KHAN','IT',3.90),
('HASSAN ALI','SE',2.95),
('FATIMA NOOR','CS',3.75),
('AHMED IQBAL','IT',2.50),
('AYESHA MALIK','AI',3.60),
('BILAL TARIQ','CS',3.10),
('ZARA MEHMOOD','SE',3.85);
INSERT INTO COURSES(COURSE_NAME,CREDIT_HOURS) VALUES('DATABASE SYSTEMS',3),
('DATA STRUCTURES',4),
('OPERATING SYSTEM',3),
('ARTIFICIAL INTELLIGENCE',3),
('WEB PROGRAMMING',4);
INSERT INTO ENROLLMENTS(STUDENT_ID,COURSE_ID,SEMESTER,MARKS) VALUES(1,1,'SPRING',85),
(1,2,'SPRING',79),
(2,1,'FALL',91),
(2,3,'FALL',87),
(3,2,'SPRING',66),
(4,4,'FALL',92),
(4,5,'FALL',84),
(5,3,'SPRING',58),
(6,4,'SPRING',90),
(7,1,'FALL',73),
(7,5,'SPRING',88),
(2,5,'SPRING',95),
(3,1,'FALL',60),
(6,2,'FALL',80),
(4,1,'SPRING',88);

SELECT STUDENT_ID,COURSE_ID FROM ENROLLMENTS WHERE SEMESTER='SPRING';
SELECT NAME FROM STUDENTS WHERE DEPARTMENT='CS' OR GPA>3.8;
SELECT DEPARTMENT,AVG(GPA) AS AVGMARKS FROM STUDENTS WHERE GPA> 3.0 GROUP BY DEPARTMENT ORDER BY AVGMARKS DESC ;
SELECT STUDENT_ID,MARKS FROM ENROLLMENTS WHERE MARKS>85 ;
SELECT NAME,DEPARTMENT FROM STUDENTS WHERE GPA BETWEEN 3.00 AND 3.80;
SELECT NAME FROM STUDENTS WHERE (NAME LIKE 'A%' OR NAME LIKE '%Q')AND DEPARTMENT='IT';
SELECT SEMESTER,COUNT(STUDENT_ID) AS TOTALSTD FROM ENROLLMENTS GROUP BY SEMESTER;
SELECT COURSE_ID,AVG(MARKS) AS AVGMARKS FROM ENROLLMENTS GROUP BY COURSE_ID;
SELECT SEMESTER,MAX(MARKS) AS MAXMARKS,MIN(MARKS) AS MINMARKS FROM ENROLLMENTS GROUP BY SEMESTER; 
SELECT DISTINCT SEMESTER,COURSE_ID FROM ENROLLMENTS ;
ALTER TABLE STUDENTS ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE STUDENTS MODIFY DEPARTMENT VARCHAR(5);
SET SQL_SAFE_UPDATES=0;
DELETE FROM COURSES WHERE CREDIT_HOURS<3;