CREATE DATABASE STD;
USE STD;
CREATE TABLE USER(
USER_ID INT PRIMARY KEY,
USERNAME VARCHAR(50),
PASSWORD VARCHAR(50)
);
CREATE TABLE STUD(
STD_ID INT PRIMARY KEY,
STDNAME VARCHAR(50),
PRG VARCHAR(50),
SEM VARCHAR(50)
);